/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 road.glb --transform 
Files: road.glb [39.39MB] > /home/ikkiren/TranscendanceGame/road-transformed.glb [1.48MB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/road-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={8.075}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/road-transformed.glb')
